# Site settings
title: Martin Basterrechea
email: martinbaste@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my awesome portfolio site. I am in the process of creating it, 
  and I hope I remember to change this before it is done. I'll write something 
  just in case: I am a Bioinformatician that has fun doing Web Development.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://martinbaste.com" # the base hostname & protocol for your site
twitter_username: partinez
github_username:  martinbaste

# Build settings
markdown: kramdown
